// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AddToCartAvatar from "./islands/AddToCartAvatar.tsx";
import * as $AddToCartButton from "./islands/AddToCartButton.tsx";
import * as $BawFilters from "./islands/BawFilters.tsx";
import * as $BreadcrumbControls from "./islands/BreadcrumbControls.tsx";
import * as $HeaderButton from "./islands/HeaderButton.tsx";
import * as $HeaderModals from "./islands/HeaderModals.tsx";
import * as $HeaderSearchbar from "./islands/HeaderSearchbar.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $OutOfStock from "./islands/OutOfStock.tsx";
import * as $ProductCardSimilar from "./islands/ProductCardSimilar.tsx";
import * as $ProductDetails from "./islands/ProductDetails.tsx";
import * as $ProductGallery from "./islands/ProductGallery.tsx";
import * as $ProductImageZoom from "./islands/ProductImageZoom.tsx";
import * as $ProductReviews from "./islands/ProductReviews.tsx";
import * as $ProductVariantSelectorPDP from "./islands/ProductVariantSelectorPDP.tsx";
import * as $ProductVariantSelectorPLP from "./islands/ProductVariantSelectorPLP.tsx";
import * as $ReadMore from "./islands/ReadMore.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $ShareButton from "./islands/ShareButton.tsx";
import * as $ShippingSimulation from "./islands/ShippingSimulation.tsx";
import * as $Sidebar from "./islands/Sidebar.tsx";
import * as $SizebayButtons from "./islands/SizebayButtons.tsx";
import * as $SizebayIframe from "./islands/SizebayIframe.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $StoreMap from "./islands/StoreMap.tsx";
import * as $StorePageCep from "./islands/StorePageCep.tsx";
import * as $StorePageContainer from "./islands/StorePageContainer.tsx";
import * as $StorePageMapList from "./islands/StorePageMapList.tsx";
import * as $StorePageSelectStates from "./islands/StorePageSelectStates.tsx";
import * as $WishlistButton from "./islands/WishlistButton.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AddToCartAvatar.tsx": $AddToCartAvatar,
    "./islands/AddToCartButton.tsx": $AddToCartButton,
    "./islands/BawFilters.tsx": $BawFilters,
    "./islands/BreadcrumbControls.tsx": $BreadcrumbControls,
    "./islands/HeaderButton.tsx": $HeaderButton,
    "./islands/HeaderModals.tsx": $HeaderModals,
    "./islands/HeaderSearchbar.tsx": $HeaderSearchbar,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/OutOfStock.tsx": $OutOfStock,
    "./islands/ProductCardSimilar.tsx": $ProductCardSimilar,
    "./islands/ProductDetails.tsx": $ProductDetails,
    "./islands/ProductGallery.tsx": $ProductGallery,
    "./islands/ProductImageZoom.tsx": $ProductImageZoom,
    "./islands/ProductReviews.tsx": $ProductReviews,
    "./islands/ProductVariantSelectorPDP.tsx": $ProductVariantSelectorPDP,
    "./islands/ProductVariantSelectorPLP.tsx": $ProductVariantSelectorPLP,
    "./islands/ReadMore.tsx": $ReadMore,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/ShareButton.tsx": $ShareButton,
    "./islands/ShippingSimulation.tsx": $ShippingSimulation,
    "./islands/Sidebar.tsx": $Sidebar,
    "./islands/SizebayButtons.tsx": $SizebayButtons,
    "./islands/SizebayIframe.tsx": $SizebayIframe,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/StoreMap.tsx": $StoreMap,
    "./islands/StorePageCep.tsx": $StorePageCep,
    "./islands/StorePageContainer.tsx": $StorePageContainer,
    "./islands/StorePageMapList.tsx": $StorePageMapList,
    "./islands/StorePageSelectStates.tsx": $StorePageSelectStates,
    "./islands/WishlistButton.tsx": $WishlistButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
