// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/createReview.ts";
import * as $$$$$$$$$1 from "./actions/putCouponInOrderForm.ts";
import * as $$$$$$$$$2 from "./actions/removeCouponInOrderForm.ts";
import * as $$$$$$$$$3 from "./actions/sendClientEmail.ts";
import * as $$$$$$$$$$$0 from "./apps/analytics.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$0 from "./handlers/vtexProxyForAbTest.ts";
import * as $$$0 from "./loaders/getPickupPointsByCep.ts";
import * as $$$1 from "./loaders/getPickupPointsByStateGql.ts";
import * as $$$2 from "./loaders/getProfileByEmail.ts";
import * as $$$3 from "./loaders/reviewsandratings.ts";
import * as $$$$$$0 from "./sections/AuthIframe.tsx";
import * as $$$$$$1 from "./sections/BannerCardPosition.tsx";
import * as $$$$$$2 from "./sections/BannerFourCards.tsx";
import * as $$$$$$3 from "./sections/BannerFull.tsx";
import * as $$$$$$4 from "./sections/BannerGrid.tsx";
import * as $$$$$$5 from "./sections/BannerMovieImg.tsx";
import * as $$$$$$6 from "./sections/BannerPLP.tsx";
import * as $$$$$$7 from "./sections/BannerPLPCampaign.tsx";
import * as $$$$$$8 from "./sections/BawBanner.tsx";
import * as $$$$$$9 from "./sections/BawFeatures.tsx";
import * as $$$$$$10 from "./sections/BawHighlights.tsx";
import * as $$$$$$11 from "./sections/BawProductShelf.tsx";
import * as $$$$$$12 from "./sections/Carousel.tsx";
import * as $$$$$$13 from "./sections/ContentExchangeReturn.tsx";
import * as $$$$$$14 from "./sections/CookieConsent.tsx";
import * as $$$$$$15 from "./sections/DesignSystem.tsx";
import * as $$$$$$16 from "./sections/FaqExchangeReturn.tsx";
import * as $$$$$$17 from "./sections/Features.tsx";
import * as $$$$$$18 from "./sections/Footer.tsx";
import * as $$$$$$19 from "./sections/HeadBanner.tsx";
import * as $$$$$$20 from "./sections/Header.tsx";
import * as $$$$$$34 from "./sections/headerExchangeReturn.tsx";
import * as $$$$$$21 from "./sections/Highlights.tsx";
import * as $$$$$$22 from "./sections/LinkTree.tsx";
import * as $$$$$$23 from "./sections/ProductDetails.tsx";
import * as $$$$$$24 from "./sections/ProductShelf.tsx";
import * as $$$$$$25 from "./sections/ReadMore.tsx";
import * as $$$$$$28 from "./sections/SearchBreadControls.tsx";
import * as $$$$$$29 from "./sections/SearchResult.tsx";
import * as $$$$$$26 from "./sections/SEOPDPBaw.tsx";
import * as $$$$$$27 from "./sections/SEOPLPBaw.tsx";
import * as $$$$$$30 from "./sections/SetSellerCookie.tsx";
import * as $$$$$$31 from "./sections/StorePage.tsx";
import * as $$$$$$32 from "./sections/WhatsApp.tsx";
import * as $$$$$$33 from "./sections/WishlistGallery.tsx";

const manifest = {
  "loaders": {
    "site/loaders/getPickupPointsByCep.ts": $$$0,
    "site/loaders/getPickupPointsByStateGql.ts": $$$1,
    "site/loaders/getProfileByEmail.ts": $$$2,
    "site/loaders/reviewsandratings.ts": $$$3,
  },
  "handlers": {
    "site/handlers/vtexProxyForAbTest.ts": $$$$0,
  },
  "sections": {
    "site/sections/AuthIframe.tsx": $$$$$$0,
    "site/sections/BannerCardPosition.tsx": $$$$$$1,
    "site/sections/BannerFourCards.tsx": $$$$$$2,
    "site/sections/BannerFull.tsx": $$$$$$3,
    "site/sections/BannerGrid.tsx": $$$$$$4,
    "site/sections/BannerMovieImg.tsx": $$$$$$5,
    "site/sections/BannerPLP.tsx": $$$$$$6,
    "site/sections/BannerPLPCampaign.tsx": $$$$$$7,
    "site/sections/BawBanner.tsx": $$$$$$8,
    "site/sections/BawFeatures.tsx": $$$$$$9,
    "site/sections/BawHighlights.tsx": $$$$$$10,
    "site/sections/BawProductShelf.tsx": $$$$$$11,
    "site/sections/Carousel.tsx": $$$$$$12,
    "site/sections/ContentExchangeReturn.tsx": $$$$$$13,
    "site/sections/CookieConsent.tsx": $$$$$$14,
    "site/sections/DesignSystem.tsx": $$$$$$15,
    "site/sections/FaqExchangeReturn.tsx": $$$$$$16,
    "site/sections/Features.tsx": $$$$$$17,
    "site/sections/Footer.tsx": $$$$$$18,
    "site/sections/HeadBanner.tsx": $$$$$$19,
    "site/sections/Header.tsx": $$$$$$20,
    "site/sections/headerExchangeReturn.tsx": $$$$$$34,
    "site/sections/Highlights.tsx": $$$$$$21,
    "site/sections/LinkTree.tsx": $$$$$$22,
    "site/sections/ProductDetails.tsx": $$$$$$23,
    "site/sections/ProductShelf.tsx": $$$$$$24,
    "site/sections/ReadMore.tsx": $$$$$$25,
    "site/sections/SearchBreadControls.tsx": $$$$$$28,
    "site/sections/SearchResult.tsx": $$$$$$29,
    "site/sections/SEOPDPBaw.tsx": $$$$$$26,
    "site/sections/SEOPLPBaw.tsx": $$$$$$27,
    "site/sections/SetSellerCookie.tsx": $$$$$$30,
    "site/sections/StorePage.tsx": $$$$$$31,
    "site/sections/WhatsApp.tsx": $$$$$$32,
    "site/sections/WishlistGallery.tsx": $$$$$$33,
  },
  "actions": {
    "site/actions/createReview.ts": $$$$$$$$$0,
    "site/actions/putCouponInOrderForm.ts": $$$$$$$$$1,
    "site/actions/removeCouponInOrderForm.ts": $$$$$$$$$2,
    "site/actions/sendClientEmail.ts": $$$$$$$$$3,
  },
  "apps": {
    "site/apps/analytics.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
